name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install packages
      run: |
        sudo apt-get -y install cmake ninja
    - name: build
      run: |
        mkdir build
        cd build 
        cmake .. -GNinja -DFETCHCONTENT_QUIET=OFF
        ninja package-llvm-toolchain

