name: Build

on:
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: ~

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install packages
      run: |
        sudo apt-get -y install cmake ninja-build meson
    - name: configure
      run: |
       git config --global user.email "pawel@32bitmicro.com"
       git config --global user.name "Pawel Wodnicki"
    - name: build
      run: |
        mkdir build
        cd build 
        cmake .. -GNinja -DFETCHCONTENT_QUIET=OFF
        ninja package-llvm-toolchain
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: LLVM-ETOOL
        path: build/LLVM-ETOOL*.tar.xz
        retention-days: 5

